/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as UserSplatRouteImport } from './routes/user/$'
import { Route as ExploreCategorySlugRouteImport } from './routes/explore/$categorySlug'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime/$animeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSplatRoute = UserSplatRouteImport.update({
  id: '/user/$',
  path: '/user/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategorySlugRoute = ExploreCategorySlugRouteImport.update({
  id: '/explore/$categorySlug',
  path: '/explore/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/explore/$categorySlug': typeof ExploreCategorySlugRoute
  '/user/$': typeof UserSplatRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/explore/$categorySlug': typeof ExploreCategorySlugRoute
  '/user/$': typeof UserSplatRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/explore/$categorySlug': typeof ExploreCategorySlugRoute
  '/user/$': typeof UserSplatRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime/$animeId'
    | '/explore/$categorySlug'
    | '/user/$'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime/$animeId'
    | '/explore/$categorySlug'
    | '/user/$'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/anime/$animeId'
    | '/explore/$categorySlug'
    | '/user/$'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  ExploreCategorySlugRoute: typeof ExploreCategorySlugRoute
  UserSplatRoute: typeof UserSplatRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$': {
      id: '/user/$'
      path: '/user/$'
      fullPath: '/user/$'
      preLoaderRoute: typeof UserSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$categorySlug': {
      id: '/explore/$categorySlug'
      path: '/explore/$categorySlug'
      fullPath: '/explore/$categorySlug'
      preLoaderRoute: typeof ExploreCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  ExploreCategorySlugRoute: ExploreCategorySlugRoute,
  UserSplatRoute: UserSplatRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
